import React, { useState } from 'react';
import { Presentation, FileText, ChevronLeft, ChevronRight, Edit2, Sparkles, Copy, Check, Loader } from 'lucide-react';
import { callGemini } from '../utils/gemini';
import { formatMarkdown, parseBold } from '../utils/markdown';

export default function PitchGenerator({ 
  slides, 
  setSlides, 
  prd, 
  setPrd, 
  documents, 
  currentIdea, 
  apiKey,
  showToast
}) {
  const [subTab, setSubTab] = useState('pitch'); // 'pitch' or 'prd'
  const [currentSlideIdx, setCurrentSlideIdx] = useState(0);
  const [isEditing, setIsEditing] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  // Edit slide form states
  const [slideTitle, setSlideTitle] = useState('');
  const [slideSubtitle, setSlideSubtitle] = useState('');
  const [slideBullets, setSlideBullets] = useState('');

  const notify = (title, message, type = 'info', diagnostic = null) => {
    if (showToast) {
      showToast({ title, message, type, diagnostic });
    } else {
      alert(`${title}: ${message}`);
    }
  };

  const safeSlides = Array.isArray(slides) ? slides : [];
  const currentSlide = safeSlides[currentSlideIdx] || { title: 'No Slides', subtitle: '', bullets: [] };

  const handleStartEdit = () => {
    setSlideTitle(currentSlide.title);
    setSlideSubtitle(currentSlide.subtitle || '');
    setSlideBullets(currentSlide.bullets.join('\n'));
    setIsEditing(true);
  };

  const handleSaveEdit = (e) => {
    e.preventDefault();
    const updatedBullets = slideBullets.split('\n').filter(b => b.trim() !== '');
    
    setSlides(prev => {
      const copy = [...prev];
      copy[currentSlideIdx] = {
        ...copy[currentSlideIdx],
        title: slideTitle,
        subtitle: slideSubtitle,
        bullets: updatedBullets
      };
      return copy;
    });
    setIsEditing(false);
  };

  const handlePrevSlide = () => {
    if (currentSlideIdx > 0) {
      setCurrentSlideIdx(prev => prev - 1);
      setIsEditing(false);
    }
  };

  const handleNextSlide = () => {
    if (currentSlideIdx < safeSlides.length - 1) {
      setCurrentSlideIdx(prev => prev + 1);
      setIsEditing(false);
    }
  };

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(prd);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownloadPrdPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    
    const htmlContent = `
      <html>
        <head>
          <title>${currentIdea.title || 'ClaimScout'} - Product Requirements Document (PRD)</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
              color: #111827;
              padding: 40px;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
            }
            h1 { font-size: 26px; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-bottom: 20px; color: #1e3a8a; }
            h2 { font-size: 20px; margin-top: 24px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; color: #1e40af; }
            h3 { font-size: 16px; margin-top: 18px; color: #1d4ed8; }
            p { font-size: 14px; margin: 10px 0; }
            ul, ol { padding-left: 20px; font-size: 14px; }
            li { margin: 6px 0; }
            strong { font-weight: 700; color: #111827; }
            .meta-box {
              background: #f3f4f6;
              border: 1px solid #e5e7eb;
              border-radius: 8px;
              padding: 16px;
              margin-bottom: 24px;
              font-size: 13px;
            }
          </style>
        </head>
        <body>
          <h1>Product Requirements Document (PRD)</h1>
          <div class="meta-box">
            <strong>Project Title:</strong> ${currentIdea.title || 'Untitled Startup'}<br/>
            <strong>Core Description:</strong> ${currentIdea.description || 'N/A'}<br/>
            <strong>Generated By:</strong> ClaimScout AI
          </div>
          <div>
            ${prd.split('\n').map(line => {
              const clean = line.trim();
              if (clean.startsWith('### ')) return `<h3>${clean.replace('### ', '')}</h3>`;
              if (clean.startsWith('## ')) return `<h2>${clean.replace('## ', '')}</h2>`;
              if (clean.startsWith('# ')) return `<h1>${clean.replace('# ', '')}</h1>`;
              if (clean.startsWith('- ') || clean.startsWith('* ')) return `<li>${clean.substring(2)}</li>`;
              if (clean === "") return `<br/>`;
              const parsed = clean.replace(/\\*\\*([^*]+)\\*\\*/g, '<strong>$1</strong>');
              return `<p>${parsed}</p>`;
            }).join('\n')}
          </div>
          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            };
          </script>
        </body>
      </html>
    `;
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  const handleDownloadSlidesPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    
    const slidesHtml = safeSlides.map((slide, idx) => `
      <div class="slide-page">
        <div class="slide-container">
          <div class="slide-left-col">
            <span class="slide-tag">ClaimScout Deck - Slide ${idx + 1}</span>
            <h2 class="slide-title">${slide.title}</h2>
            ${slide.subtitle ? `<p class="slide-subtitle">${slide.subtitle}</p>` : ''}
            <div class="slide-decor"></div>
          </div>
          <div class="slide-right-col">
            <ul>
              ${slide.bullets.map(b => `<li>${b.replace(/\\*\\*([^*]+)\\*\\*/g, '<strong>$1</strong>')}</li>`).join('')}
            </ul>
          </div>
        </div>
      </div>
    `).join('\n');

    const htmlContent = `
      <html>
        <head>
          <title>${currentIdea.title || 'ClaimScout'} - Pitch Slide Deck</title>
          <style>
            @page {
              size: A4 landscape;
              margin: 0;
            }
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
              color: #ffffff;
              background: #0d1426;
              margin: 0;
              padding: 0;
            }
            .slide-page {
              width: 297mm;
              height: 210mm;
              box-sizing: border-box;
              padding: 25mm;
              page-break-after: always;
              display: flex;
              flex-direction: column;
              justify-content: center;
              position: relative;
              background: radial-gradient(circle at 80% 20%, #0e1e38 0%, #070a13 100%);
              border-bottom: 1px solid #1e293b;
            }
            .slide-container {
              display: grid;
              grid-template-columns: 1.2fr 1.8fr;
              gap: 20mm;
              align-items: center;
            }
            .slide-left-col {
              border-right: 2px solid #3b82f6;
              padding-right: 10mm;
            }
            .slide-tag {
              font-size: 12px;
              color: #3b82f6;
              font-weight: 700;
              text-transform: uppercase;
              letter-spacing: 1.5px;
            }
            .slide-title {
              font-size: 32px;
              margin: 10px 0;
              color: #ffffff;
              font-weight: 700;
              line-height: 1.2;
            }
            .slide-subtitle {
              font-size: 16px;
              color: #94a3b8;
              margin: 10px 0 0 0;
              font-weight: 400;
            }
            .slide-right-col ul {
              list-style: none;
              padding: 0;
              margin: 0;
            }
            .slide-right-col li {
              font-size: 18px;
              line-height: 1.6;
              margin: 12px 0;
              color: #cbd5e1;
              position: relative;
              padding-left: 24px;
            }
            .slide-right-col li::before {
              content: "→";
              position: absolute;
              left: 0;
              color: #3b82f6;
              font-weight: bold;
            }
            .slide-right-col li strong {
              color: #38bdf8;
              font-weight: 700;
            }
            @media print {
              .slide-page {
                border-bottom: none;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }
            }
          </style>
        </head>
        <body>
          ${slidesHtml}
          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            };
          </script>
        </body>
      </html>
    `;
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  // Agentic compilation of pitch & PRD based on current library
  const handleRegenerate = async () => {
    if (!apiKey) {
      notify("API Key Required", "Please enter a Gemini API Key in Settings (top-right) to generate customized slides.", "info");
      return;
    }
    
    setIsRegenerating(true);
    try {
      const docsContext = documents.map(doc => `Title: ${doc.title}\nContent: ${doc.content}`).join("\n\n");
      const prompt = `Based on the startup idea: "${currentIdea.title} - ${currentIdea.description}" and the references:\n${docsContext}\nGenerate an 7-slide Pitch Deck and a Product Requirement Document (PRD) in JSON. Structure matches exactly:
      {
        "slides": [
          { "id": 1, "title": "Slide Title", "subtitle": "Slide Subtitle", "bullets": ["bullet 1", "bullet 2"] }
        ],
        "prd": "# PRD Title\\n\\n## Section..."
      }`;

      const contents = [{ role: "user", parts: [{ text: prompt }] }];
      const result = await callGemini(apiKey, contents, true);

      setSlides(result.slides);
      setPrd(result.prd);
      setCurrentSlideIdx(0);
      notify("Generation Success", "Pitch Deck & PRD successfully compiled from workspace references!", "success");
    } catch (e) {
      console.error(e);
      let diag = null;
      if (e.message && e.message.includes("Failed to fetch")) {
        diag = "This is typically caused by adblockers (e.g. Brave Shields, uBlock Origin) blocking client-side requests to generativeai.googleapis.com. Try disabling your shields or network firewall.";
      }
      notify("Generation Failed", "Failed to compile slides. Try entering a different prompt or check your API key.", "error", diag);
    } finally {
      setIsRegenerating(false);
    }
  };

  // Helper to render markdown headings into simple HTML tags
  const renderPRD = (text) => {
    return formatMarkdown(text);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      {/* Sub tabs header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <div style={{ display: 'flex', gap: '8px', background: 'rgba(0,0,0,0.2)', padding: '3px', borderRadius: '8px' }}>
          <button 
            className={`btn ${subTab === 'pitch' ? 'btn-primary' : ''}`}
            onClick={() => setSubTab('pitch')}
            style={{ padding: '6px 12px', fontSize: '12px' }}
          >
            <Presentation size={14} style={{ marginRight: '6px' }} />
            Pitch Deck
          </button>
          <button 
            className={`btn ${subTab === 'prd' ? 'btn-primary' : ''}`}
            onClick={() => setSubTab('prd')}
            style={{ padding: '6px 12px', fontSize: '12px' }}
          >
            <FileText size={14} style={{ marginRight: '6px' }} />
            PRD Document
          </button>
        </div>

        <div>
          {subTab === 'prd' ? (
            <div style={{ display: 'flex', gap: '8px' }}>
              <button className="btn" onClick={handleCopyToClipboard}>
                {isCopied ? <Check size={14} className="text-emerald" /> : <Copy size={14} />}
                {isCopied ? 'Copied!' : 'Copy PRD'}
              </button>
              <button className="btn" onClick={handleDownloadPrdPDF} style={{ borderColor: 'var(--accent-cyan)', color: 'var(--accent-cyan)' }}>
                Download PDF
              </button>
            </div>
          ) : (
            <div style={{ display: 'flex', gap: '8px' }}>
              <button className="btn" onClick={handleDownloadSlidesPDF} style={{ borderColor: 'var(--accent-cyan)', color: 'var(--accent-cyan)' }}>
                Download Deck PDF
              </button>
              {apiKey && (
                <button className="btn" onClick={handleRegenerate} disabled={isRegenerating}>
                  {isRegenerating ? <Loader size={14} className="loader" /> : <Sparkles size={14} />}
                  Generate customized Deck & PRD
                </button>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Workspace Area */}
      <div style={{ flex: 1, minHeight: 0 }}>
        {subTab === 'pitch' ? (
          <div className="pitch-container">
            {/* Slide */}
            <div className="slide-deck-viewer">
              <div className="slide-bg-glow" />
              
              <div className="slide-content-grid">
                <div className="slide-left-col">
                  <span className="slide-tag">ClaimScout Deck</span>
                  <h2 className="slide-title">{currentSlide.title}</h2>
                  {currentSlide.subtitle && <p className="slide-subtitle">{currentSlide.subtitle}</p>}
                  <div className="slide-decor-bar" />
                </div>

                <div className="slide-right-col">
                  <div className="slide-bullets">
                    {currentSlide.bullets.map((bullet, idx) => (
                      <div key={idx} className="slide-bullet-item">
                        <ChevronRight size={16} />
                        <p>{parseBold(bullet)}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="slide-footer">
                <span className="slide-indicator">Slide {currentSlideIdx + 1} of {safeSlides.length}</span>
                <div className="slide-nav-buttons">
                  <button className="btn btn-icon" onClick={handlePrevSlide} disabled={currentSlideIdx === 0}>
                    <ChevronLeft size={16} />
                  </button>
                  <button className="btn btn-icon" onClick={handleNextSlide} disabled={currentSlideIdx === safeSlides.length - 1}>
                    <ChevronRight size={16} />
                  </button>
                </div>
              </div>
            </div>

            {/* Slide Editor Panel */}
            <div className="slide-editor-panel">
              <h3>Slide Editor</h3>
              {!isEditing ? (
                <div>
                  <p style={{ fontSize: '13px', color: 'var(--text-secondary)', marginBottom: '14px', lineHeight: 1.4 }}>
                    You can directly edit the content of this slide (Title, Subtitle, and bullet points) to customize your pitch, or regenerate it using AI references.
                  </p>
                  <button className="btn" onClick={handleStartEdit} style={{ width: '100%', justifyContent: 'center' }}>
                    <Edit2 size={13} style={{ marginRight: '6px' }} />
                    Edit Slide Content
                  </button>
                </div>
              ) : (
                <form onSubmit={handleSaveEdit} style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  <div className="input-group" style={{ margin: 0 }}>
                    <label>Title</label>
                    <input 
                      type="text" 
                      className="input-text" 
                      value={slideTitle}
                      onChange={(e) => setSlideTitle(e.target.value)}
                      required 
                    />
                  </div>
                  <div className="input-group" style={{ margin: 0 }}>
                    <label>Subtitle</label>
                    <input 
                      type="text" 
                      className="input-text" 
                      value={slideSubtitle}
                      onChange={(e) => setSlideSubtitle(e.target.value)}
                    />
                  </div>
                  <div className="input-group" style={{ margin: 0 }}>
                    <label>Bullets (one per line)</label>
                    <textarea 
                      className="textarea-custom" 
                      style={{ minHeight: '120px' }}
                      value={slideBullets}
                      onChange={(e) => setSlideBullets(e.target.value)}
                      required
                    />
                  </div>
                  <div style={{ display: 'flex', gap: '8px', marginTop: '4px' }}>
                    <button type="submit" className="btn btn-primary" style={{ flex: 1, justifyContent: 'center' }}>
                      Save Changes
                    </button>
                    <button type="button" className="btn" style={{ flex: 1, justifyContent: 'center' }} onClick={() => setIsEditing(false)}>
                      Cancel
                    </button>
                  </div>
                </form>
              )}
            </div>
          </div>
        ) : (
          /* PRD */
          <div className="prd-viewer">
            <div className="prd-content">
              {renderPRD(prd)}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
